export const START_LOGIN_USER = 'START_LOGIN_USER';

export const ERROR_LOGIN_USER = 'ERROR_LOGIN_USER';

export const COMPLETE_LOGIN_USER = 'COMPLETE_LOGIN_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const IS_LOGGED = 'IS_LOGGED';

export const GET_EVENTS = 'GET_EVENTS';


export const START_ADD_EVENT_TYPE = 'START_ADD_EVENT_TYPE';

export const ERROR_ADD_EVENT_TYPE = 'ERROR_ADD_EVENT_TYPE';

export const COMPLETE_ADD_EVENT_TYPE = 'COMPLETE_ADD_EVENT_TYPE';

export const SET_EVENT_TYPE_NAME = 'SET_EVENT_TYPE_NAME';


export const START_GET_EVENT_TYPES = 'START_GET_EVENT_TYPES';

export const ERROR_GET_EVENT_TYPES = 'ERROR_GET_EVENT_TYPES';

export const COMPLETE_GET_EVENT_TYPES = 'COMPLETE_GET_EVENT_TYPES';


export const START_GET_EVENTS = 'START_GET_EVENTS';

export const ERROR_GET_EVENTS = 'ERROR_GET_EVENTS';

export const COMPLETE_GET_EVENTS = 'COMPLETE_GET_EVENTS';


export const START_ADD_EVENT = 'START_ADD_EVENT';

export const ERROR_ADD_EVENT = 'ERROR_ADD_EVENT';

export const COMPLETE_ADD_EVENT = 'COMPLETE_ADD_EVENT';




